services:
  db:
    image: postgis/postgis:17-3.5
    container_name: aquaguard_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aquaguard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aquaguard"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
